# Project-wide Gradle settings.

# JVM args (Kotlin compiler hiç değilse 4G ister)
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError

# Configuration cache & parallel builds
org.gradle.parallel=true
org.gradle.configuration-cache=false

# AndroidX migration
android.useAndroidX=true

# Kotlin
kotlin.code.style=official

# Non-transitive R class generation
android.nonTransitiveRClass=true
